<?xml version="1.0"?>
<robot name="kulbu" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="PI" value="3.1415926535897931"/>

    <xacro:property name="chassisHeight" value="0.060"/>
    <xacro:property name="chassisLength" value="0.160"/>
    <xacro:property name="chassisWidth" value="0.160"/>
    <xacro:property name="chassisMass" value="50"/>

    <xacro:property name="wheelWidth" value="0.025"/>
    <xacro:property name="wheelRadius" value="0.030"/>
    <xacro:property name="wheelPos" value="0.2"/>
    <xacro:property name="wheelMass" value="5"/>

    <xacro:property name="casterRadius" value="0.015"/>

    <arg name="gui" value="true"/>

    <xacro:include filename="$(find kulbu_description)/urdf/kulbabu.gazebo" />
    <xacro:include filename="$(find kulbu_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find kulbu_description)/urdf/macros.xacro" />

    <link name="base_link" />

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
    </joint>

    <link name='chassis_link'>
        <collision>
            <origin xyz="0 0 ${-0.015+wheelRadius+chassisHeight/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${chassisLength/2}" length="${chassisHeight}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 ${-0.015+wheelRadius+chassisHeight/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${chassisLength/2}" length="${chassisHeight}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <inertial>
            <origin xyz="${-chassisLength/8} 0 ${-0.015+wheelRadius+chassisHeight/2}" rpy="0 0 0"/>
            <mass value="${chassisMass}"/>
            <cylinder_inertia m="${chassisMass}" r="${chassisLength/2}" h="${chassisHeight}"/>
        </inertial>
    </link>

    <link name='caster_link'>
        <collision name='caster_collision'>
            <origin xyz="${casterRadius-chassisLength/2} 0 ${wheelRadius-casterRadius}" rpy="0 0 0" />
            <geometry>
                <sphere radius="${casterRadius}" />
            </geometry>

            <surface>
                <friction>
                    <ode>
                        <mu>0</mu>
                        <mu2>0</mu2>
                        <slip1>1.0</slip1>
                        <slip2>1.0</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>
        <visual name='caster_visual'>
            <origin xyz="${casterRadius-chassisLength/2} 0 ${wheelRadius-casterRadius}" rpy="0 0 0" />
            <geometry>
                <sphere radius="${casterRadius}" />
            </geometry>
            <material name="green"/>
        </visual>
    </link>

    <gazebo reference="caster_link">
        <mu1 value="0"/>
        <mu2 value="0"/>
        <kp  value="10000000.0" />
        <kd  value="1.0" />
        <fdir1 value="0 0 0"/>
        <material>Gazebo/Green</material>
    </gazebo>

    <joint name="caster_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="caster_link"/>
    </joint>

    <!-- EffortJointInterface/VelocityJointInterface -->
    <wheel fb="mid"   lr="left"  tX="0"  tY="1"   mu="0.3" interface="VelocityJointInterface" />
    <wheel fb="mid"   lr="right" tX="0"  tY="-1"  mu="0.3" interface="VelocityJointInterface" />

    <!-- Range
    https://jsfiddle.net/MrYellow/2fdtnsbw/
    -2.356194490 -135 -0.056568542494923796 -0.05656854249492381
    -1.832595715 -105 -0.02070552360820167 -0.07727406610312547
    -1.308996939 -75 0.02070552360820166 -0.07727406610312547
    -0.785398163 -45 0.05656854249492381 -0.056568542494923796
    -0.261799388 -15 0.07727406610312545 -0.020705523608201673
    0.261799388 15 0.07727406610312547 0.02070552360820164
    0.785398163 45 0.056568542494923824 0.05656854249492378
    1.308996939 75 0.02070552360820171 0.07727406610312545
    1.832595715 105 -0.02070552360820163 0.07727406610312547
    2.356194490 135 -0.056568542494923796 0.05656854249492381
    2.879793266 165 -0.07727406610312547 0.020705523608201645
    3.403392041 195 -0.07727406610312545 -0.020705523608201694
    -->
    <sensor_gazebo_range name="range_1l" linX="0.07727406610312547"  linY="0.02070552360820164" linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="0.261799388" />
    <sensor_gazebo_range name="range_2l" linX="0.056568542494923824" linY="0.05656854249492378" linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="0.785398163" />
    <sensor_gazebo_range name="range_3l" linX="0.02070552360820171"  linY="0.07727406610312545" linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="1.308996939" />
    <sensor_gazebo_range name="range_4l" linX="-0.02070552360820163" linY="0.07727406610312547" linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="1.832595715" />

    <sensor_gazebo_range name="range_1r" linX="0.07727406610312547"  linY="-0.02070552360820164" linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="-0.261799388" />
    <sensor_gazebo_range name="range_2r" linX="0.056568542494923824" linY="-0.05656854249492378" linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="-0.785398163" />
    <sensor_gazebo_range name="range_3r" linX="0.02070552360820171"  linY="-0.07727406610312545" linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="-1.308996939" />
    <sensor_gazebo_range name="range_4r" linX="-0.02070552360820163" linY="-0.07727406610312547" linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="-1.832595715" />


    <!--sensor_bump name="bump_l" linX="${chassisLength/2}" linY="0.15"  linZ="${chassisHeight}" angR="0" angP="0" angY="0.785398163" /-->
    <!--sensor_bump name="bump_r" linX="${chassisLength/2}" linY="-0.15" linZ="${chassisHeight}" angR="0" angP="0" angY="-0.785398163" /-->

    <!-- IMU -->
    <joint name="imu_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="chassis_link"/>
        <child link="imu_link"/>
    </joint>

    <link name="imu_link">
        <collision>
            <origin xyz="0 0 ${chassisHeight}" rpy="0 0 0"/>
            <geometry>
                <box size="0.0 0.0 0.0"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${chassisHeight}" rpy="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
            <material name="yellow"/>
        </visual>

        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>

</robot>
