<?xml version="1.0"?>
<robot name="kulbu" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="PI" value="3.1415926535897931"/>

    <xacro:property name="chassisHeight" value="0.060"/>
    <xacro:property name="chassisLength" value="0.160"/>
    <xacro:property name="chassisWidth" value="0.160"/>
    <xacro:property name="chassisMass" value="10"/>

    <xacro:property name="wheelWidth" value="0.025"/>
    <xacro:property name="wheelRadius" value="0.030"/>
    <xacro:property name="wheelPos" value="0.2"/>
    <xacro:property name="wheelMass" value="2"/>

    <xacro:property name="casterRadius" value="0.015"/>
    <xacro:property name="casterMass" value="1"/>

    <xacro:property name="bumperHeight" value="0.020"/>
    <xacro:property name="bumperLength" value="${0.70710678118*chassisLength}"/>
    <xacro:property name="bumperWidth" value="${0.70710678118*chassisWidth}"/>
    <xacro:property name="bumperMass" value="0.5"/>

    <xacro:arg name="gui" default="true"/>

    <xacro:include filename="$(find kulbu_description)/urdf/kulbabu.gazebo" />
    <xacro:include filename="$(find kulbu_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find kulbu_description)/urdf/macros.xacro" />

    <link name="base_link" />

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
    </joint>

    <link name='chassis_link'>
        <collision>
            <origin xyz="0 0 ${-0.015+wheelRadius+chassisHeight/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${chassisLength/2}" length="${chassisHeight}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 ${-0.015+wheelRadius+chassisHeight/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${chassisLength/2}" length="${chassisHeight}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <inertial>
            <origin xyz="0 0 ${-0.015+wheelRadius+chassisHeight/2}" rpy="0 0 0"/>
            <mass value="${chassisMass}"/>
            <cylinder_inertia m="${chassisMass}" r="${chassisLength/2}" h="${chassisHeight}"/>
        </inertial>
    </link>

    <joint name="caster_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="caster_link"/>
    </joint>

    <link name='caster_link'>
        <collision name='caster_collision'>
            <origin xyz="${casterRadius-chassisLength/2} 0 ${wheelRadius-casterRadius}" rpy="0 0 0" />
            <geometry>
                <sphere radius="${casterRadius}" />
            </geometry>

            <surface>
                <!--contact>
                    <ode>
                        <kp>1e+08</kp>
                        <kd>10000</kd>
                    </ode>
                </contact-->
                <friction>
                    <ode>
                        <mu>0</mu>
                        <mu2>0</mu2>
                        <slip1>1.0</slip1>
                        <slip2>1.0</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>
        <visual name='caster_visual'>
            <origin xyz="${casterRadius-chassisLength/2} 0 ${wheelRadius-casterRadius}" rpy="0 0 0" />
            <geometry>
                <sphere radius="${casterRadius}" />
            </geometry>
            <material name="green"/>
        </visual>
        <inertial>
            <origin xyz="${casterRadius-chassisLength/2} 0 ${wheelRadius-casterRadius}" rpy="0 0 0" />
            <mass value="${casterMass}"/>
            <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
        </inertial>
    </link>

    <joint name="bumper_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="bumper_link"/>
    </joint>

    <link name='bumper_link'>
        <collision name='bumper_collision'>
            <origin xyz="${0.015+bumperLength-chassisLength/2} 0 ${wheelRadius+bumperHeight/2}" rpy="0 0 ${45*(PI/180)}" />
            <geometry>
                <box size="${bumperLength} ${bumperWidth} ${bumperHeight}"/>
            </geometry>

            <surface>
                <!--contact>
                    <ode>
                        <kp>1e+08</kp>
                        <kd>10000</kd>
                    </ode>
                </contact-->
                <friction>
                    <ode>
                        <mu>0</mu>
                        <mu2>0</mu2>
                        <slip1>1.0</slip1>
                        <slip2>1.0</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>
        <visual name='bumper_visual'>
            <origin xyz="${0.015+bumperLength-chassisLength/2} 0 ${wheelRadius+bumperHeight/2}" rpy="0 0 ${45*(PI/180)}" />
            <geometry>
                <box size="${bumperLength} ${bumperWidth} ${bumperHeight}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <inertial>
            <origin xyz="${0.015+bumperLength-chassisLength/2} 0 ${wheelRadius+bumperHeight/2}" rpy="0 0 ${45*(PI/180)}" />
            <mass value="${bumperMass}"/>
            <box_inertia m="${bumperMass}" x="${bumperLength/2}" y="${bumperLength/2}" z="${bumperHeight/2}"/>
        </inertial>
    </link>

    <!-- EffortJointInterface/VelocityJointInterface -->
    <wheel fb="mid"   lr="left"  tX="0"  tY="0.75"   mu="0.3" interface="VelocityJointInterface" />
    <wheel fb="mid"   lr="right" tX="0"  tY="-0.75"  mu="0.3" interface="VelocityJointInterface" />

    <!-- Range
    https://jsfiddle.net/MrYellow/2fdtnsbw/

    -2.356194490 -135 -0.05126524163602469 -0.051265241636024694
    -1.832595715 -105 -0.01876438076993276 -0.07002962240595745
    -1.308996939 -75 0.018764380769932754 -0.07002962240595745
    -0.785398163 -45 0.051265241636024694 -0.05126524163602469
    -0.261799388 -15 0.07002962240595743 -0.018764380769932764
    0.261799388 15 0.07002962240595745 0.018764380769932733
    0.785398163 45 0.05126524163602471 0.051265241636024673
    1.308996939 75 0.018764380769932802 0.07002962240595743
    1.832595715 105 -0.01876438076993273 0.07002962240595746
    2.356194490 135 -0.05126524163602469 0.051265241636024694
    2.879793266 165 -0.07002962240595745 0.01876438076993274
    -->

    <sensor_gazebo_range name="range_1l" linX="0.07002962240595745"   linY="0.018764380769932733"  linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="0.261799388" />
    <sensor_gazebo_range name="range_2l" linX="0.05126524163602471"   linY="0.051265241636024673"  linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="0.785398163" />
    <sensor_gazebo_range name="range_3l" linX="0.018764380769932802"  linY="0.07002962240595745"   linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="1.308996939" />
    <sensor_gazebo_range name="range_4l" linX="-0.01876438076993273"  linY="0.07002962240595745"   linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="1.832595715" />

    <sensor_gazebo_range name="range_1r" linX="0.07002962240595745"   linY="-0.018764380769932733" linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="-0.261799388" />
    <sensor_gazebo_range name="range_2r" linX="0.05126524163602471"   linY="-0.051265241636024673" linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="-0.785398163" />
    <sensor_gazebo_range name="range_3r" linX="0.018764380769932802"  linY="-0.07002962240595745"  linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="-1.308996939" />
    <sensor_gazebo_range name="range_4r" linX="-0.01876438076993273"  linY="-0.07002962240595745"  linZ="${0.045+wheelRadius+chassisHeight/2}" angR="0" angP="0" angY="-1.832595715" />

    <!--sensor_bump name="bump_l" linX="${0.045+chassisLength/4}" linY="${chassisLength/4}"  linZ="${chassisHeight/2}" angR="0" angP="0" angY="${45*(PI/180)}" />
    <sensor_bump name="bump_r" linX="${0.045+chassisLength/4}" linY="-${chassisLength/4}" linZ="${chassisHeight/2}" angR="0" angP="0" angY="-${45*(PI/180)}" /-->

    <!-- IMU -->
    <!--joint name="imu_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="chassis_link"/>
        <child link="imu_link"/>
    </joint>

    <link name="imu_link">
        <collision>
            <origin xyz="0 0 ${chassisHeight}" rpy="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${chassisHeight}" rpy="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
            <material name="yellow"/>
        </visual>

        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link-->

</robot>
