<?xml version="1.0"?>
<robot name="kulbu" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <macro name="cylinder_inertia" params="m r h">
      <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
        iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
        izz="${m*r*r/2}"
      />
    </macro>

    <macro name="box_inertia" params="m x y z">
      <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
        iyy="${m*(x*x+z*z)/12}" iyz = "0"
        izz="${m*(x*x+z*z)/12}"
      />
    </macro>

    <macro name="sphere_inertia" params="m r">
      <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
        iyy="${2*m*r*r/5}" iyz = "0"
        izz="${2*m*r*r/5}"
      />
    </macro>

    <macro name="wheel" params="fb lr tX tY mu interface">

        <link name="${fb}_${lr}_wheel">
          <collision>
            <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
            <geometry>
              <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
            </geometry>
          </collision>

          <visual>
            <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
            <geometry>
              <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
            </geometry>
            <material name="black"/>
          </visual>

          <inertial>
            <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
            <mass value="${wheelMass}"/>
            <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
          </inertial>
        </link>

        <gazebo reference="${fb}_${lr}_wheel">
            <mu1 value="${mu}"/>
            <mu2 value="${mu}"/>
            <kp  value="10000000.0" />
            <kd  value="1.0" />
            <fdir1 value="0 0 0"/>
            <material>Gazebo/Black</material>
        </gazebo>

        <joint name="${fb}_${lr}_wheel_joint" type="continuous">
            <parent link="chassis_link"/>
            <child link="${fb}_${lr}_wheel"/>
            <origin xyz="${tX*chassisLength/2} ${tY*wheelWidth/2+tY*chassisWidth/2} ${wheelRadius}" rpy="0 0 0" />
            <axis xyz="0 1 0" rpy="0 0 0" />
            <limit effort="100" velocity="100"/>
            <joint_properties damping="0.0" friction="0.0"/>
        </joint>

        <transmission name="${fb}_${lr}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${fb}_${lr}_wheel_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${fb}_${lr}_wheel_joint">
                <hardwareInterface>${interface}</hardwareInterface>
            </joint>
        </transmission>

    </macro>
</robot>